# Generated by Django 4.2.7 on 2023-12-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='createb_by',
            new_name='created_by',
        ),
    ]
