# Generated by Django 4.2.7 on 2024-01-11 19:02

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_alter_conversationmessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='modified_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
