# Generated by Django 4.2.7 on 2024-02-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_alter_conversation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='content',
            field=models.TextField(verbose_name='متن پیام'),
        ),
    ]
