# Generated by Django 4.2.7 on 2024-02-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_item_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='reject_msg',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='آیا محصول مورد تایید است؟'),
        ),
    ]
